name: easy_amplicon_0.1
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - fastp
  - trimmomatic
  - trim-galore
  - cutadapt
  - seqkit
  - samtools
  - bwa-mem2
  - mmseqs2
  - mafft
  - trimal
  - raxml
  - fasttree
  - blast
  - pigz
  - vsearch
